SupermecardoPeruanos/Web.FidelizacionClientes/Controllers/ProductoCanjeController.cs
using Business.FidelizacionClientes.Implement;
using Business.FidelizacionClientes.Interfaces;
using Model.FidelizacionClientes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.FidelizacionClientes.Controllers
{
    public class ProductoCanjeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ObtenerProductosCanje(int? tipoId, int? categoriaId)
        {
            IProductoCanjeBL productoCanjeBL = new ProductoCanjeBL();

            var productos = productoCanjeBL.GetProductosCanje(tipoId, categoriaId);

            var data = new
            {
                success = productos.Any(),
                productos = productos
            };

            return Json(data, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult ObtenerProductoCanje(int id)
        {
            IProductoCanjeBL productoCanjeBL = new ProductoCanjeBL();

            var producto = productoCanjeBL.Get(id);

            var data = new
            {
                success = producto != null,
                producto = producto
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ObtenerCategorias()
        {
            ICategoriaBL categoriaBL = new CategoriaBL();

            var categorias = categoriaBL.GetAll();

            var data = new
            {
                success = categorias.Any(),
                categorias = categorias
            };

            return Json(data, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult Registrar(Producto producto)
        {
            try
            {
                IProductoCanjeBL productoCanjeBL = new ProductoCanjeBL();

                productoCanjeBL.Insertar(producto);

                var data = new
                {
                    success = true,
                    mensaje = "Se registro satisfactoriamente"
                };

                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Editar(Producto producto)
        {
            try
            {
                IProductoCanjeBL productoCanjeBL = new ProductoCanjeBL();
                productoCanjeBL.Update(producto);

                var data = new
                {
                    success = true,
                    mensaje = "Se actualizó satisfactoriamente"
                };

                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Eliminar(int id)
        {
            try
            {
                IProductoCanjeBL productoCanjeBL = new ProductoCanjeBL();
                productoCanjeBL.Delete(id);

                var data = new
                {
                    success = true,
                    mensaje = "Se eliminó satisfactoriamente"
                };

                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SupermecardoPeruanos/Web.FidelizacionClientes/Views/ProductoCanje/EditarModal.cshtml
<!-- Modal -->


<!-- Modal -->
<div class="modal fade" id="modal-editar" role="dialog">
    <div class="modal-dialog-clientes">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Editar Producto Canje</h4>
            </div>
            <div class="modal-body">
                <form id="seccion-datos-producto-editar" class="well">
                    <h5 class="subtitulos">Datos del Producto Canje</h5>
                    <div class="form-horizontal col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-codigo-editar">Código:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-codigo-editar" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-nombre-editar">Nombre:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-nombre-editar" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-valor-canje-editar">Valor Canje:</label>
                            <div class="col-md-8">
                                <input type="number" class="form-control" id="txt-valor-canje-editar" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="select-tipo-editar">Tipo:</label>
                            <div class="col-md-8">
                                <select id="select-tipo-editar" class="form-control col-md-8" required>
                                    <option value="">- Seleccionar -</option>
                                    <option value="0">Producto</option>
                                    <option value="1">Servicio</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="select-categoria-editar">Categoría:</label>
                            <div class="col-md-8">
                                <select id="select-categoria-editar" class="form-control col-md-8" required>
                                    <option value="">- Seleccionar -</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-stock-editar">Stock:</label>
                            <div class="col-md-8">
                                <input type="number" class="form-control" id="txt-stock-editar" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-horizontal col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-descripcion-editar">Descripción:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-descripcion-editar" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-condiciones-editar">Condiciones:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-condiciones-editar" required>
                            </div>
                        </div>
                    </div>
                    <button id="btn-editar" type="submit" class="btn btn-default col-md-12" form="seccion-datos-producto-editar">
                        Editar Producto Canje
                    </button>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>

SupermecardoPeruanos/Web.FidelizacionClientes/Views/ProductoCanje/EliminarModal.cshtml
<!-- Modal -->
<div class="modal fade" id="modal-eliminar" role="dialog">
    <div class="modal-dialog-clientes">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Eliminar Producto Canje</h4>
            </div>
            <div class="modal-body">
                <form id="seccion-datos-producto-eliminar" class="well">
                    <h5 class="subtitulos"> ¿Está seguro de eliminarlo?</h5>
                    <div class="form-horizontal col-md-12">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-codigo-eliminar">Id:</label>
                            <div class="col-md-8">
                                <input type="number" class="form-control" id="txt-codigo-eliminar" readonly>
                            </div>
                        </div>
                    </div>
                    <button id="btn-eliminar" type="submit" class="btn btn-default col-md-12" form="seccion-datos-producto-eliminar">
                        Si
                    </button>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>

SupermecardoPeruanos/Web.FidelizacionClientes/Views/ProductoCanje/Index.cshtml
@{
    ViewBag.Title = "Productos Canje";
}

@Styles.Render("http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css")
@Scripts.Render("http://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js")

<div id="clientes" class="container-fluid">
    <section id="seccion-filtros" style="padding-bottom: 30px;">
        <h5 class="subtitulos">Producto Canje</h5>
        <div class="row form-group">
            <div class="col-md-6">
                <label class="control-label col-md-4" for="select-tipo" style="padding: 10px;">Tipo:</label>
                <select id="select-tipo" class="form-control col-md-8">
                    <option value="">- Todos -</option>
                    <option value="0">Producto</option>
                    <option value="1">Servicio</option>
                </select>
            </div>
            <div class="col-md-6">
                <label class="control-label col-md-4" for="select-categoria" style="padding: 10px;">Categoría:</label>
                <select id="select-categoria" class="form-control col-md-8">
                    <option value="">- Todos -</option>
                </select>
            </div>
        </div>
    </section>
    <section id="seccion-grilla">
        <table id="table_productos" class="display">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Valor Canje</th>
                    <th>Tipo</th>
                    <th>Categoria</th>
                    <th>Stock</th>
                    <th>Editar / Eliminar</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </section>
    <section>
        <div class="row content">
            <button id="btn-agregar-producto" class="btn btn-primary col-md-12" data-toggle="modal" data-target="#modal-registrar" data-remote="false">
                Registrar Producto
            </button>
        </div>
    </section>
</div>

@Html.Partial("~/Views/ProductoCanje/EditarModal.cshtml")
@Html.Partial("~/Views/ProductoCanje/RegistrarModal.cshtml")
@Html.Partial("~/Views/ProductoCanje/EliminarModal.cshtml")

@Scripts.Render("~/Scripts/ProductoCanje/ProductoCanjeModule.js")
<script>
    $(document).ready(function () {

        var productoCanjeModule = new ProductoCanjeModule(
            {
                urlObtenerProductosCanje: '@Url.Action("ObtenerProductosCanje", "ProductoCanje")',
                urlObtenerCategorias: '@Url.Action("ObtenerCategorias", "ProductoCanje")',
                urlObtenerProductoCanje: '@Url.Action("ObtenerProductoCanje", "ProductoCanje")',
                urlRegistrar: '@Url.Action("Registrar", "ProductoCanje")',
                urlEditar: '@Url.Action("Editar", "ProductoCanje")',
                urlEliminar: '@Url.Action("Eliminar", "ProductoCanje")'
            }
        );

        productoCanjeModule.initialize();
    });

</script>

SupermecardoPeruanos/Web.FidelizacionClientes/Views/ProductoCanje/RegistrarModal.cshtml
<!-- Modal -->
<div class="modal fade" id="modal-registrar" role="dialog">
    <div class="modal-dialog-clientes">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Registro de Producto Canje</h4>
            </div>
            <div class="modal-body">
                <form id="seccion-datos-producto" class="well">
                    <h5 class="subtitulos">Datos del Producto Canje</h5>
                    <div class="form-horizontal col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-codigo">Código:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-codigo" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-nombre">Nombre:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-nombre" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-valor-canje">Valor Canje:</label>
                            <div class="col-md-8">
                                <input type="number" class="form-control" id="txt-valor-canje" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="select-tipo-registrar">Tipo:</label>
                            <div class="col-md-8">
                                <select id="select-tipo-registrar" class="form-control col-md-8" required>
                                    <option value="">- Seleccionar -</option>
                                    <option value="0">Producto</option>
                                    <option value="1">Servicio</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="select-categoria-registrar">Categoría:</label>
                            <div class="col-md-8">
                                <select id="select-categoria-registrar" class="form-control col-md-8" required>
                                    <option value="">- Seleccionar -</option>     
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-stock">Stock:</label>
                            <div class="col-md-8">
                                <input type="number" class="form-control" id="txt-stock" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-horizontal col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-descripcion">Descripción:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-descripcion" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="txt-condiciones">Condiciones:</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="txt-condiciones" required>
                            </div>
                        </div>
                    </div>
                    <button id="btn-registrar" type="submit" class="btn btn-default col-md-12" form="seccion-datos-producto">
                        Registrar Producto Canje
                    </button>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>