SupermecardoPeruanos/Web.FidelizacionClientes/Controllers/AfiliacionController.cs
using Business.FidelizacionClientes.Implement;
using Business.FidelizacionClientes.Interfaces;
using Common.FidelizacionClientes;
using Model.FidelizacionClientes;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Web.FidelizacionClientes.Controllers
{
    public class AfiliacionController : Controller
    {
        // GET: Afiliacion
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult BuscarAfiliacionCliente(string numeroDocumento)
        {
            IClienteBL clienteBL = new ClienteBL();
            ICalificacionBL calificacionBL = new CalificacionBL();
            IAfiliacionBL afiliacionBL = new AfiliacionBL();
            

            Calificacion calificacion = new Calificacion();
            AfiliacionTarjetaOH afiliacion = new AfiliacionTarjetaOH();
            List<Object> _infocorp = new List<object>();
            String estado = String.Empty;

            Cliente cliente = clienteBL.GetCliente(numeroDocumento);
            bool existeCliente = (cliente != null && cliente.Codigo != 0);
            if (existeCliente)
            {
                calificacion = calificacionBL.GetByCliente(cliente.Codigo);
                afiliacion = afiliacionBL.GetByCliente(cliente.Codigo);
                List<Infocorp> infocorp = afiliacionBL.GetInfocorpByCliente(cliente.Codigo);
                _infocorp = new List<Object>();
                infocorp.ForEach(x => _infocorp.Add(new
                {
                    EntidadFinanciera = x.EntidadFinanciera,
                    MontoDeuda = x.MontoDeuda,
                    CalificacionSBS = x.CalificacionSBS
                }));

                estado = afiliacionBL.ConsultarEstadoSol(numeroDocumento);


            }

            var data = new
            {
                Cliente = cliente,
                Calificacion = calificacion,
                Afiliacion = afiliacion,
                Infocorp = _infocorp,
                Estado = estado,
                success = existeCliente
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        /*
         * Ingresos mayor igual a 2000 para una tarjeta de linea de credido de menor igual a 1000 
            Ingresos mayor igual a 4000 para una tarjeta de linea de credido de menor igual a 2000
            Ingresos mayor igual a 6000 para una tarjeta de linea de credido de menor igual a 3000

            Debe contar con Calificacion SBS A o B

         */
        public JsonResult Evaluar(int codigoCliente, int numeroDocumento)
        {
            ICalificacionBL calificacionBL = new CalificacionBL();
            IAfiliacionBL afiliacionBL = new AfiliacionBL();

            Calificacion calificacion = calificacionBL.GetByCliente(codigoCliente);
            AfiliacionTarjetaOH afiliacion = afiliacionBL.GetByCliente(codigoCliente);
            List<Infocorp> infocorp = afiliacionBL.GetInfocorpByCliente(codigoCliente);

            decimal ingresoTotal = calificacion.SueldoCliente + calificacion.OtrosIngresos;
            bool isCalifica = false;
            string tipo = String.Empty;

            if (((ingresoTotal >= CalificacionEnum.SueldoIngresoMinimoA && calificacion.LineaCredito >= CalificacionEnum.LineaCreditoMinimo && calificacion.LineaCredito <= CalificacionEnum.LineaCreditoMaximoA) ||
                (ingresoTotal >= CalificacionEnum.SueldoIngresoMinimoB && calificacion.LineaCredito > CalificacionEnum.LineaCreditoMaximoA && calificacion.LineaCredito <= CalificacionEnum.LineaCreditoMaximoB) ||
                (ingresoTotal >= CalificacionEnum.SueldoIngresoMinimoC && calificacion.LineaCredito > CalificacionEnum.LineaCreditoMaximoB && calificacion.LineaCredito <= CalificacionEnum.LineaCreditoMaximoC)))
            {
                foreach (var item in infocorp)
                {
                    isCalifica = item.CalificacionSBS.Equals("0") || item.CalificacionSBS.Equals("1");
                    if (ingresoTotal >= CalificacionEnum.SueldoIngresoMinimoC)
                    {
                        tipo = "Black";
                    }
                    else if (ingresoTotal >= CalificacionEnum.SueldoIngresoMinimoB)
                    {
                        tipo = "Gold";
                    }
                    else if (ingresoTotal >= CalificacionEnum.SueldoIngresoMinimoA)
                    {
                        tipo = "Plata";
                    }
                }
            }

            if (isCalifica == false){

                afiliacionBL.UpdateSolicitudDes(numeroDocumento);
            }

            var data = new
            {
                EstadoAfiliacion = isCalifica,
                NumeroTarjeta = afiliacion.NumeroTarjeta,
                Tipo = tipo
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarAfiliacion(int codigoCliente, string numero, string tipo)
        {
            IAfiliacionBL afiliacionBL = new AfiliacionBL();

            afiliacionBL.InsertCliente(codigoCliente, numero, tipo);

            var data = new
            {
                success = 1,
                message = "Se registró existosamente."
            };

            return Json(data, JsonRequestBehavior.AllowGet);

        }
    }
}

SupermecardoPeruanos/Web.FidelizacionClientes/Views/Afiliacion/AfiliacionModal.cshtml
<!-- Modal -->
<div class="modal fade" id="modal-afiliar" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Afiliación de Tarjeta OH</h4>
            </div>
            <div class="modal-body">
                <b> <p id="lblMensajeAfiliacion"></p></b>
                <div id="msjs">
                    <b>
                        Número de Tarjeta:
                    </b><p id="lblNumeroTarjeta"></p>
                    <b> Tipo Tarjeta: </b><p id="lblTipo"></p>
                    <button id="btnRegistrarAfiliacion" class="btn btn-default col-md-12" data-toggle="modal" data-target="#modal-afiliar" data-remote="false">
                        Registrar Afiliación
                    </button>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>

    </div>
</div>

SupermecardoPeruanos/Web.FidelizacionClientes/Views/Afiliacion/Index.cshtml
@{
    ViewBag.Title = "Afiliar Cliente a Tarjeta OH";
}

@Styles.Render("http://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css")
@Scripts.Render("http://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js")

<div id="afiliar-tarjeta-oh" class="container-fluid">
    <div id="mensajeAprobado" class="row content mensaje-aprobado" style="display: none;"> La Solicitud del Cliente  
                <label id="lblNombres"></label> 
                <label id="lblApellidos"></label>
                ya se encuentra Aprobada.
    </div>
    <div class="row content">
        <div id="seccion-buscar-cliente" class="col-md-2 well">
            <h5 class="subtitulos">Búsqueda de Cliente</h5>
            <div class="input-group">
                <input id="txtBusquedaPorNumDoc" maxlength="8" type="text" class="form-control" placeholder="# de Documento" onKeypress="if (event.keyCode < 45 || event.keyCode > 57) event.returnValue = false;">
                <div class="input-group-btn">
                    <button id="btnBuscarCliente" class="btn btn-default">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-5 ">
            <div id="seccion-datos-cliente" class="well secciones-afiliar">
                <h5 class="subtitulos">Datos del Cliente</h5>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-md-4" for="txtCodigo">Código:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="txtCodigo" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="txtNombres">Nombres:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="txtNombres" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="txtApellidos">Apellidos:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="txtApellidos" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4" for="txtNumeroDocumento">Núm. de Doc.:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="txtNumeroDocumento" readonly>
                        </div>
                    </div>
                </div>
            </div>

            <div id="seccion-ingresos" class="well secciones-afiliar-2">
                <h5 class="subtitulos">Ingresos mensuales</h5>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-md-8" for="txtSueldoMensual">Sueldo Mensual:</label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" id="txtSueldoMensual" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-8" for="txtOtrosIngresos">Otros Ingresos:</label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" id="txtOtrosIngresos" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-8" for="txtLineaCredito">Linea de Crédito Aprobada:</label>
                        <div class="col-md-4">
                            <input type="text" class="form-control" id="txtLineaCredito" readonly>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-5">

            <div id="seccion-deudas" class="well secciones-afiliar">
                <h5 class="subtitulos">Deudas en Otras Entidades</h5>
                <table id="table_deudas" class="display">
                    <thead>
                        <tr>
                            <th>Entidad Financiera</th>
                            <th>Monto</th>
                            <th>Estado</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>

            <div id="seccion-evaluacion" class="well secciones-afiliar-2">
                <h5 class="subtitulos">Nro. de Tarjeta OH</h5>
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-md-5" for="txtNumeroTarjeta">Número de Tarjeta:</label>
                        <div class="col-md-7">
                            <input type="text" class="form-control" id="txtNumeroTarjeta" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row content"> 
        <button id="btnEvaluar" class="btn btn-primary col-md-12" data-toggle="modal" data-target="#modal-afiliar" data-remote="false" disabled>
            Evaluar
        </button> 
    </div>
</div>

@Html.Partial("~/Views/Afiliacion/AfiliacionModal.cshtml")

@Scripts.Render("~/Scripts/Afiliacion/AfiliacionModule.js")
<script>
    $(document).ready(function () {

        var afilacionModule = new AfiliacionModule(
            {
                urlBuscarAfiliacionCliente: '@Url.Action("BuscarAfiliacionCliente", "Afiliacion")',
                urlEvaluar: '@Url.Action("Evaluar", "Afiliacion")',
                urlRegistrar: '@Url.Action("RegistrarAfiliacion", "Afiliacion")'
            }
        );

        afilacionModule.initialize();
    });

</script>