SupermecardoPeruanos/Web.CanjePuntos/Models/CarModel.cs
using Business.FidelizacionClientes.Implement;
using Business.FidelizacionClientes.Interfaces;
using Model.FidelizacionClientes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace Web.CanjePuntos.Models
{
    public class CarModel
    {
        [DataType(DataType.Text)]
        public string Detail { get; set; }
        public List<CanjePedido> ListCanjePedido;
        public CarModel()
        {
            ListCanjePedido = new List<CanjePedido>();
        }
        public Boolean AddItem(int idProducto)
        {
            CanjePedido itemVenta = new CanjePedido();
            itemVenta.Productos = new Producto { Id = idProducto };
            ListCanjePedido.Add(itemVenta);
            return true;
        }
        public void CargarDatos()
        {
            ICanjePedidoBL canjePedido = new CanjePedidoBL();
            ListCanjePedido = canjePedido.ListarCanjePedido();
        }

    }
}

SupermecardoPeruanos/Web.CanjePuntos/Controllers/CanjePedidoController.cs
using Business.FidelizacionClientes.Implement;
using Business.FidelizacionClientes.Interfaces;
using Model.FidelizacionClientes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.CanjePuntos.Models;

namespace Web.CanjePuntos.Controllers
{
    public class CanjePedidoController : Controller
    {
        private CanjePedido canjePedido;
        // GET: CanjePedido
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ConfirmarPedidoCanje()
        {
            return View();
        }
        public JsonResult GuardarItem(int idProducto)
        {
            CarModel viewmodel = new CarModel();
            viewmodel.CargarDatos();
            var retorno = viewmodel.AddItem(idProducto);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

    }
}

SupermecardoPeruanos/Web.CanjePuntos/Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.CanjePuntos.Controllers
{
    //[Authorize]
    public class CatalogoController : Controller
    {
        // GET: Catalogo
        public ActionResult Index()
        {
            return View();
        }
    }
}

SupermecardoPeruanos/Web.CanjePuntos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.CanjePuntos.ActionFilters;

namespace Web.CanjePuntos.Controllers
{
    [AuthorizationFilter]
    public class HomeController : Controller
    {      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SupermecardoPeruanos/Web.CanjePuntos/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.CanjePuntos.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

SupermecardoPeruanos/Web.CanjePuntos/Views/CanjePedido/ConfirmarPedidoCanje.cshtml
@model Web.CanjePuntos.Models.CarModel
@{
    ViewBag.Title = "Confirmar Pedido Canje";
}

<h2>Confirmar Perdido Canje</h2>

<div class="row">

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <p><h4>Ingreso de Pedido Realizado Con Exito</h4></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>Estimado Cliente @*<b>Cliente Testing</b>*@ su compra se ha realizado de manera exitosa.</p>
                    <p>Recuerde que despues de confirmar el ingreso de pedido canje <b>NO PODRA REALIZAR CAMBIO DE LA MISMA</b></p>
                    <hr />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p><h4>Detalle del Pedido Producto-Canje</h4></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <table id="tblDetail" class="table">
                            <thead>
                                <tr>
                                    <th class="col-xs-7">Producto</th>
                                    <th class="col-xs-2 text-right">Cantidad</th>
                                    <th class="col-xs-3 text-right">Puntos</th>
                                    <th class="col-xs-3 text-right">Total</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot>
                                <tr>
                                    <th></th>
                                    <th colspan="2" class="text-right">Valor total de canje</th>
                                    <th class="text-right"><span id="lblSumpunt">----</span></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-9">&nbsp;</div>
                <div class="col-md-3 text-right">
                        <button id="btnConfirmarPedido" data-dismiss="alert" class="btn btn-primary btn-block ">Confirmar Pedido Canje</button>
                        </div>
            </div>

        </div>
    </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


<script>
    $("#btnConfirmarPedido").click(function () {
        alert("Canje realizado exitosamente");
        location.href = "/Catalogo";
    });
    
    var productos = JSON.parse(localStorage.getItem("productos"));
    
    loadGrid();

    function loadGrid() {
        //$.ajax({
        //    type: "GET",
        //    url: 'http://localhost:52131/api/CarritoCanje/',
        //    //ids = parametro del controlador
        //    data: { ids: carritoCanje.idProductos },
        //    success: function (data) {
        //        listItems(data);
        //    },
        //    error: function (xhr, ajaxOptions, thrownError) {
        //        alert("Mensaje", thrownError);
        //    }
        //});
        //return false;

        var content = "";
        var sum = 0;
        var total = 0;

        $.each(productos, function (index, value) {
            content += '<tr>';
            content += '<td class="col-xs-7">' + value.Nombre + '</td>';
            content += '<td class="col-xs-2 text-right">' + value.Cantidad + '</td>';
            content += '<td class="col-xs-3 text-right">' + value.Puntos + '</td>';
            content += '<td class="col-xs-3 text-right">' + value.Puntos * value.Cantidad + '</td>';
            content += '</tr>';

            sum += parseInt(value.Puntos * value.Cantidad);
            total = sum 
        });

        $('#tblDetail>tbody').append(content);
        $('#lblSumpunt').html(sum);
    }


</script>

SupermecardoPeruanos/Web.CanjePuntos/Views/CanjePedido/Index.cshtml
@{
    ViewBag.Title = "Carrito de canje";
}

@Styles.Render("https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css")
@Scripts.Render("https://code.jquery.com/ui/1.12.1/jquery-ui.js")
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<div class="container-fluid">
    <div class="row content">
        <div class="col text-center">
            <h4 class="display-4">Carrito de Productos - Pedido Canje</h4>
            <hr />
        </div>
    </div>
</div>
<div id="lstCarrito" class="container-fluid">
    
</div>
<div>
    <table id="listaProducto">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Cantidad</th>
                <th>Puntos</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
            </tr>
        </tbody>
        

    </table>
</div>
<div id="footerDiv" class="container-fluid">
    <!--Footer Table-->
    <div class="row">
        <div class="col-md-11 text-right">
            <label class="col-md-9 col-form-label text-right">Total Puntos:</label>
            <div class="col-md-3">
                <input type="text" id="txtTotal" class="form-control text-right" readonly value="3" />
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <hr />
    </div>
</div>
<div id="gotoConfirmDiv" class="row">
    <div class="col text-center">
        <a href="~/CanjePedido/ConfirmarPedidoCanje" class="btn btn-primary" data-badge="">Finalizar Ingreso de Pedido</a>
    </div>
</div>

@Html.Partial("~/Views/Catalogo/ProductoModal.cshtml")
@Scripts.Render("~/Scripts/CanjePedido/CanjePedidoModule.js")

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


<script>
     $(document).ready(function () {

         var canjePedidoModule = new CanjePedidoModule();
    });
</script>

SupermecardoPeruanos/Web.CanjePuntos/Views/CanjePedido/ObtenerProductosCanje.cshtml
@model IEnumerable<Web.CanjePuntos.Models.CarModel>

@{
    ViewBag.Title = "ObtenerProductosCanje";
}

<h2>ObtenerProductosCanje</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Detail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Detail)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

SupermecardoPeruanos/Web.CanjePuntos/Views/Login/index.cshtml
<!DOCTYPE html>
<html lang="en-us">
    <head>
        <title>SafetyAuth</title>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta charset="UTF-8">

        <!-- load bootstrap and fontawesome via CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' type='text/css'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
        <link rel="stylesheet" href="~/Content/main.css">
        
        <!-- load angular via CDN -->
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
        <script src="https://code.angularjs.org/1.5.8/angular-resource.min.js"></script>
        <script src="https://code.angularjs.org/1.5.8/angular-route.min.js"></script>
        <script src="~/Scripts/app.js"></script>
    </head>
    <body>
        <header>
			<nav class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="http://safetyauth.com">SafetyAuth</a>
				</div>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#/account"><i class="fa fa-home"></i>Home</a></li>
				</ul>
			</div>
			</nav>
		</header>
        <div class="container" ng-app="safetyAuthApp">
        <div ng-controller="accountController">        
                  <div class="form">
              <ul class="tab-group">
                <li class="tab active"><a href="#signup">Sign Up</a></li>
                <li class="tab"><a href="#login">Log In</a></li>
              </ul>
                
              <div class="tab-content">
                      <div id="signup">
                            <h1>Sign Up for Free</h1>
                            <form method="post">

                            <div class="top-row">
                            <div class="field-wrap">
                            <label>
                                First Name<span class="req">*</span>
                              </label>
                            <input type="text" required autocomplete="off" ng-model='accountData.firstName'/>
                          </div>

                            <div class="field-wrap">
                            <label>
                                Last Name<span class="req">*</span>
                              </label>
                            <input type="text" required autocomplete="off" ng-model='accountData.lastName'/>
                          </div>
                        </div>
                            <div class="field-wrap">
                              <label>
                                  Email Address<span class="req">*</span>
                                </label>
                              <input type="email" required autocomplete="off" ng-model='accountData.email'/>
                            </div>

                            <div class="field-wrap">
                              <label>
                                  Password<span class="req">*</span>
                                </label>
                              <input type="password" required autocomplete="off" ng-model='accountData.password'/>
                            </div>

                            <div class="field-wrap">
                              <label>
                                  Company Name<span class="req">*</span>
                                </label>
                              <input type="text" required autocomplete="off" ng-model='accountData.companyName'/>
                            </div>
                            

                                                            
                            <button type="submit" class="button button-block" ng-click='postAccount()'>Sign Up</button>
                            <div class="field-wrap">
                                    <input type="checkbox" class="checkbox"  id="accept_conditions">
					                   <label for="accept_conditions">I agree to the Terms and Conditions</label>
                            </div>
                            </form>
                    </div>
                      <div id="login">
                          <h1>Welcome Back!</h1>

                          <form method="post">

                            <div class="field-wrap">
                              <label>
                                  Email Address<span class="req">*</span>
                                </label>
                              <input type="email" required autocomplete="off" ng-model='accountData.loginEmail'/>
                            </div>

                            <div class="field-wrap">
                              <label>
                                  Password<span class="req">*</span>
                                </label>
                              <input type="password" required autocomplete="off" ng-model='accountData.loginPasssword'/>
                            </div>

                            <p class="forgot"><a href="#">Forgot Password?</a></p>

                            <button type="submit" class="button button-block" ng-click='loginAccount()' >Log In</button>

                          </form>

                        </div>                  
            </div>
            </div>
        </div>
        </div>            
    </body>
    <div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="~/Scripts/Login/main.js"></script>
    </div>
</html>

SupermecardoPeruanos/Web.CanjePuntos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canje de Puntos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Canje de Puntos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Consultar Catalogo", "Index", "Catalogo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <section>
        @RenderBody()
        </section>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>